version: '3.9'
services:
  dev:
    platform: linux/x86_64
    image: akraradets/aibrainlab.co:v0.0.1
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 1313:1313
    volumes:
      - ./:/home/project
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - NODE_OPTIONS=--openssl-legacy-provider