theme      = "chaklam"
publishDir = "docs"

title      = "AI Brain Lab"

[params]
    logo = "/img/_logo.png"

[menu]


[taxonomies]
  role = 'roles'

# https://gohugo.io/getting-started/configuration/

defaultContentLanguage = "th"
defaultContentLanguageInSubdir = 'true'

[languages.th]
    contentDir = 'content/th'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'th'

[[languages.th.menu.main]]
  name = 'หน้าหลัก'
  pageRef = '/'
  weight = 10

[[languages.th.menu.main]]
  name = 'ตัวอย่างการใช้งาน'
  pageRef = '/'
  weight = 30
  params = { section='#portfolio' }

[[languages.th.menu.main]]
name = 'ต่อกับ API ของเรา'
pageRef = '/'
weight = 40
params = { section='#' }

[[languages.th.menu.main]]
  name = 'ติตต่อ'
  pageRef = '/'
  weight = 50
  params = { section='#contact' }

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'en'

[[languages.en.menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[languages.en.menu.main]]
  name = 'Demo'
  pageRef = '/'
  weight = 30
  params = { section='#portfolio' }

[[languages.en.menu.main]]
name = 'Connect to our API'
pageRef = '/'
weight = 40
params = { section='#' }

[[languages.en.menu.main]]
  name = 'Contact Us'
  pageRef = '/'
  weight = 50
  params = { section='#contact' }
  